service {
	feature-key-file /etc/aerospike/features.conf
	cluster-name docker
}

logging {
	console {
		context any info
	}
}

network {
	service {
		address any
		port 3000
	}

	heartbeat {
		mode mesh
		address any
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		address any
		port 3001
	}
}

namespace test {
	replication-factor 2
	default-ttl 0
	nsup-period 120
	strong-consistency true

	storage-engine device {
		file /opt/aerospike/data/test.dat
		filesize 4G
		read-page-cache true
	}
}
